// Auto-generated by .git/hooks/commit-msg from the latest commit's title — do not edit by
// hand, it gets overwritten on the next commit. Purely cosmetic (the small version tag in the
// corner) — unrelated to GAME_VERSION in config.js, which drives save-data resets.
const DISPLAY_VERSION = "3.0.3";
